# src/config/skills.py

TECH_SKILLS = [
    "python",
    "sql",
    "aws",
    "s3",
    "lambda",
    "ec2",
    "docker",
    "kubernetes",
    "terraform",
    "cloudwatch",
    "postgresql",
    "redshift",
    "spark",
    "pyspark",
    "airflow",
    "pandas",
    "numpy",
    "scikit-learn",
    "pytorch",
    "tensorflow",
    "mlflow",
    "nlp",
    "embeddings",
    "vector databases",
    "tableau",
    "power bi",
    "excel",
    "a/b testing",
    "rest apis",
    "java",
    "typescript",
    "react",
    "node.js",
    "statistics",
    "data visualization",
    "ci/cd",
    "data pipelines",
    "model deployment",
    "model monitoring",
    "etl",
    "data warehousing",
    "dashboards",
    "business analytics",
    "model evaluation",
    "cloud deployment",
    "dbt",
    "linux",
    "automation scripts",
    "data modeling",
    "product metrics",
    "monitoring",
    "machine learning",
    "model evaluation",
    "mysql"
]

BASE_SKILL_IMPORTANCE = {
    "python": 5,
    "sql": 5,
    "statistics": 5,
    "java": 4,
    "c++": 4,
    "pandas": 4,
    "numpy": 4,
    "scikit-learn": 4,
    "pytorch": 4,
    "tensorflow": 4,
    "aws": 4,
    "docker": 4,
    "spark": 4,
    "pyspark": 4,
    "postgresql": 4,
    "mysql": 4,
    "rest apis": 4,
    "data pipelines": 4,
    "model deployment": 4,
    "s3": 3,
    "lambda": 3,
    "ec2": 3,
    "terraform": 3,
    "kubernetes": 3,
    "airflow": 3,
    "mlflow": 3,
    "tableau": 3,
    "power bi": 3,
    "a/b testing": 3,
    "data visualization": 3,
    "react": 3,
    "typescript": 3,
    "javascript": 3,
    "excel": 2,
    "cloudwatch": 2,
}