# src/config/skills.py

TECH_SKILLS = [
    "python",
    "sql",
    "aws",
    "s3",
    "lambda",
    "ec2",
    "docker",
    "kubernetes",
    "terraform",
    "cloudwatch",
    "postgresql",
    "redshift",
    "spark",
    "pyspark",
    "airflow",
    "pandas",
    "numpy",
    "scikit-learn",
    "pytorch",
    "tensorflow",
    "mlflow",
    "nlp",
    "embeddings",
    "vector databases",
    "tableau",
    "power bi",
    "excel",
    "a/b testing",
    "rest apis",
    "java",
    "typescript",
    "react",
    "node.js",
    "statistics",
    "data visualization",
    "ci/cd",
    "data pipelines",
    "model deployment",
    "model monitoring",
    "etl",
    "data warehousing",
]