# Generated by Django 5.2.17 on 2026-08-07 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('source_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'datasets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtractionResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=100)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('prompt_version', models.CharField(blank=True, max_length=100, null=True)),
                ('extracted_skills', models.JSONField(default=list)),
                ('raw_response', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'extraction_results',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source_type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_sources', models.IntegerField(default=0)),
                ('successful_sources', models.IntegerField(default=0)),
                ('failed_sources', models.IntegerField(default=0)),
                ('raw_job_count', models.IntegerField(default=0)),
                ('processed_job_count', models.IntegerField(default=0)),
                ('error_log', models.JSONField(default=list)),
                ('run_metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'ingestion_runs',
                'ordering': ['-started_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_id', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('experience_level', models.CharField(max_length=100)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('source_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('date_posted', models.CharField(blank=True, max_length=100, null=True)),
                ('valid_through', models.CharField(blank=True, max_length=100, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('workplace_type', models.CharField(blank=True, max_length=100, null=True)),
                ('is_remote', models.BooleanField(default=False)),
                ('address_locality', models.CharField(blank=True, max_length=255, null=True)),
                ('address_region', models.CharField(blank=True, max_length=100, null=True)),
                ('address_country', models.CharField(blank=True, max_length=100, null=True)),
                ('source_updated_at', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'job_postings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessedJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clean_title', models.CharField(max_length=255)),
                ('clean_description', models.TextField()),
                ('role_category', models.CharField(max_length=100)),
                ('extracted_skills', models.JSONField(default=list)),
                ('skills_text', models.TextField(default='')),
                ('skill_extraction_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('skill_extraction_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'processed_jobs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtractionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraction_result_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('status', models.CharField(default='open', max_length=30)),
                ('note', models.TextField(blank=True)),
                ('note_updated_by_username', models.CharField(blank=True, max_length=150)),
                ('note_updated_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by_username', models.CharField(blank=True, max_length=150)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_status', models.CharField(blank=True, default='', max_length=30)),
                ('retry_requested_by_username', models.CharField(blank=True, max_length=150)),
                ('retry_requested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_extraction_review_notes', to=settings.AUTH_USER_MODEL)),
                ('retry_requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_extraction_retries', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_extraction_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ops_extraction_reviews',
                'indexes': [models.Index(fields=['status', 'updated_at'], name='ops_extract_status_b68c5e_idx'), models.Index(fields=['retry_status', 'retry_requested_at'], name='ops_extract_retry_s_170f40_idx')],
            },
        ),
        migrations.CreateModel(
            name='OperationsAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_username', models.CharField(max_length=150)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('target_type', models.CharField(db_index=True, max_length=100)),
                ('target_id', models.PositiveIntegerField(db_index=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ops_audit_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id', 'created_at'], name='ops_audit_e_target__de56e5_idx'), models.Index(fields=['actor_username', 'created_at'], name='ops_audit_e_actor_u_09912e_idx')],
            },
        ),
    ]
